In [9]:
import pandas as pd
import json

In [33]:
file_path = "data/trendingtopic.json"

with open(file_path, "r", encoding="utf-8") as f:
    data = json.load(f)

df = pd.DataFrame(data)
df.head()

,id,text,created_at,username,likes,retweets,topic,timestamp
0,1965976495525953847,RT @chappellofliv: appreciation post for belly...,2025-09-11,bonradsinfinity,0.0,None,Winter Olympics 2026 Milano,NaN
1,1997495539236053254,@TrendSpider @GonogoCharts Reminder $NKE 2026,2025-12-07,allmarkettrades,81.0,None,Winter Olympics 2026 Milano,NaN
2,2003481439254597946,2026 #ProBowlGames Punters! https://t.co/AYsLo...,2025-12-23,NFL,69093.0,None,Winter Olympics 2026 Milano,NaN
3,2023754227521331648,"Sonda z Super Exspressu,gdzie wyniki dla Sikor...",2026-02-17,Koloproktologi1,14552.0,None,Super Bowl LX,NaN
4,2022691762251403405,@InternetH0F Windows Media Player catching str...,2026-02-14,Xfinancebull,3683.0,None,Winter Olympics 2026 Milano,NaN

In [35]:
df

,id,text,created_at,username,likes,retweets,topic,timestamp
0,1965976495525953847,RT @chappellofliv: appreciation post for belly...,2025-09-11,bonradsinfinity,0.0,None,Winter Olympics 2026 Milano,NaN
1,1997495539236053254,@TrendSpider @GonogoCharts Reminder $NKE 2026,2025-12-07,allmarkettrades,81.0,None,Winter Olympics 2026 Milano,NaN
2,2003481439254597946,2026 #ProBowlGames Punters! https://t.co/AYsLo...,2025-12-23,NFL,69093.0,None,Winter Olympics 2026 Milano,NaN
3,2023754227521331648,"Sonda z Super Exspressu,gdzie wyniki dla Sikor...",2026-02-17,Koloproktologi1,14552.0,None,Super Bowl LX,NaN
4,2022691762251403405,@InternetH0F Windows Media Player catching str...,2026-02-14,Xfinancebull,3683.0,None,Winter Olympics 2026 Milano,NaN
...,...,...,...,...,...,...,...,...
10600,2027937094933614832,RT @RealJamesWoods: Now you know why election ...,2026-03-01T00:00:00.000Z,BearlyOne,0.0,None,Bangladesh Election 2026,NaN
10601,2028077091019952435,@theskindoctor13 Bangladesh staying neutral on...,2026-03-01T00:00:00.000Z,EshanWealth,101.0,None,Bangladesh Election 2026,NaN
10602,2027976860248817809,@allenanalysis @PopWrapped We did not dodge a ...,2026-03-01T00:00:00.000Z,pez1963,131.0,None,Bangladesh Election 2026,NaN
10603,2028086396288700896,2026’s business secret,2026-03-01T00:00:00.000Z,NickSherrard,150.0,None,Bangladesh Election 2026,NaN
10604,2027923812671754427,@dandinohill @SenateGOP @LeaderJohnThune How m...,2026-03-01T00:00:00.000Z,HaleyTessIsis,1.0,None,Bangladesh Election 2026,NaN

In [36]:
df["topic"].value_counts()

topic
Winter Olympics 2026 Milano    5000
Super Bowl LX                  5000
Bangladesh Election 2026        605
Name: count, dtype: int64

In [37]:
df["created_at"].value_counts()

created_at
2026-03-01T00:00:00.000Z    597
2025-09-29                  242
2026-02-09                  165
2025-09-03                  136
2025-09-08                  123
                           ...
en                            4
 humanitarian issues          1
0                             1
 March 19                     1
27                            1
Name: count, Length: 192, dtype: int64

In [38]:
df["created_at"] = df["created_at"].astype(str).str[:10]
df["created_at"] = pd.to_datetime(df["created_at"], errors="coerce")
df

,id,text,created_at,username,likes,retweets,topic,timestamp
0,1965976495525953847,RT @chappellofliv: appreciation post for belly...,2025-09-11,bonradsinfinity,0.0,None,Winter Olympics 2026 Milano,NaN
1,1997495539236053254,@TrendSpider @GonogoCharts Reminder $NKE 2026,2025-12-07,allmarkettrades,81.0,None,Winter Olympics 2026 Milano,NaN
2,2003481439254597946,2026 #ProBowlGames Punters! https://t.co/AYsLo...,2025-12-23,NFL,69093.0,None,Winter Olympics 2026 Milano,NaN
3,2023754227521331648,"Sonda z Super Exspressu,gdzie wyniki dla Sikor...",2026-02-17,Koloproktologi1,14552.0,None,Super Bowl LX,NaN
4,2022691762251403405,@InternetH0F Windows Media Player catching str...,2026-02-14,Xfinancebull,3683.0,None,Winter Olympics 2026 Milano,NaN
...,...,...,...,...,...,...,...,...
10600,2027937094933614832,RT @RealJamesWoods: Now you know why election ...,2026-03-01,BearlyOne,0.0,None,Bangladesh Election 2026,NaN
10601,2028077091019952435,@theskindoctor13 Bangladesh staying neutral on...,2026-03-01,EshanWealth,101.0,None,Bangladesh Election 2026,NaN
10602,2027976860248817809,@allenanalysis @PopWrapped We did not dodge a ...,2026-03-01,pez1963,131.0,None,Bangladesh Election 2026,NaN
10603,2028086396288700896,2026’s business secret,2026-03-01,NickSherrard,150.0,None,Bangladesh Election 2026,NaN
10604,2027923812671754427,@dandinohill @SenateGOP @LeaderJohnThune How m...,2026-03-01,HaleyTessIsis,1.0,None,Bangladesh Election 2026,NaN

In [39]:
df["created_at"].value_counts()

created_at
2026-03-01    609
2025-09-29    242
2026-02-09    165
2025-09-03    136
2025-09-08    123
             ...
2025-11-30     18
2025-10-26     18
2025-11-23     17
2025-11-01     17
2025-10-25     10
Name: count, Length: 186, dtype: int64

In [40]:
df["created_at"].isna().sum()

np.int64(10)

In [41]:
(df["created_at"].isna().sum() / len(df)) * 100

np.float64(0.0942951438000943)

In [43]:
df_new = df.dropna(subset=["created_at"])

In [47]:
df_new = df_new.sort_values(by="created_at").reset_index(drop=True)
df_new

,id,text,created_at,username,likes,retweets,topic,timestamp
0,1960875468531621946,@PsyGuy007 bien vue super les gars...,2025-08-28,JaegerStep78492,0.0,None,Super Bowl LX,NaN
1,1960973143008292871,"You know what, I've ALSO been a splendid nigga...",2025-08-28,JSRingo,209.0,None,Super Bowl LX,NaN
2,1961159089544990909,@fashion_nfl Don’t think enough people are tal...,2025-08-28,p23rce,479.0,None,Super Bowl LX,NaN
3,1960932935676387741,RT @tahsin_adib: NINGNING telling winter it mu...,2025-08-28,hidden_faayz,0.0,None,Winter Olympics 2026 Milano,NaN
4,1961193691605078397,🤚🤚🤚💙2026!!!,2025-08-28,defloody,1.0,None,Winter Olympics 2026 Milano,NaN
...,...,...,...,...,...,...,...,...
10590,2028077091019952435,@theskindoctor13 Bangladesh staying neutral on...,2026-03-01,EshanWealth,101.0,None,Bangladesh Election 2026,NaN
10591,2027976860248817809,@allenanalysis @PopWrapped We did not dodge a ...,2026-03-01,pez1963,131.0,None,Bangladesh Election 2026,NaN
10592,"""2028160771054768308",@therealworld_ai @Cobratate 2026 https://t.co/...,2026-03-01,sollyhustles,30.0,None,Bangladesh Election 2026,NaN
10593,"""2028198130529747061",עדכון פיקוד העורף - סיום אירוע (01/03/2026 21:...,2026-03-01,Haskupim,40.0,None,Bangladesh Election 2026,NaN
10594,2027923812671754427,@dandinohill @SenateGOP @LeaderJohnThune How m...,2026-03-01,HaleyTessIsis,1.0,None,Bangladesh Election 2026,NaN

In [48]:
df_new["topic"].value_counts()

topic
Super Bowl LX                  4999
Winter Olympics 2026 Milano    4999
Bangladesh Election 2026        597
Name: count, dtype: int64

In [50]:
posts_per_month = df.groupby(df["created_at"].dt.to_period("M")).size()

print(posts_per_month)

created_at
2025-08     359
2025-09    2542
2025-10    1553
2025-11     961
2025-12    1022
2026-01    1228
2026-02    2321
2026-03     609
Freq: M, dtype: int64

In [51]:
df_new.to_csv("trendingtopic.csv", index=False)